# This is a basic workflow to help you get started with Actions

name: Deploy react app

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Node
      - name: install node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      # Install Yarn
      - name: install YARN
        uses: borales/actions-yarn@v2.0.0
        with:
         cmd: install
     # install react router
      - name: install react router
        #run: yarn add react-router-dom
        run: sudo yarn add react-router-dom
       #build react app with yarn
      - name: build react app
        run: sudo yarn build
       # install surge
      - name: install surge
        run: npm install -g surge
         # run surge
      - name: run surge
        run: surge ./build web-agency-aezaz-ali-1997-react-app.surge.sh --token ${{secrets.SURGE_TOKEN}}     
          
